### ISSUE TITLE
解码评估时报错NotImplementedError: Batch decoding is not supported yet.   

### ISSUE THREAD

**Issue by suuuuju** [jindongwang/EasyEspnet#2]
当训练完成进行解码评估时，到utils.py文件中nbest_hyps = model.recognize_batch(fbank, recog_args, char_list=None, rnnlm=None)时链接到了espnet/espnet/nets/asr_interface.py 文件中的recognize_batch函数，然而该函数内容为
```
def recognize_batch(self, x, recog_args, char_list=None, rnnlm=None):
        """Beam search implementation for batch.

        :param torch.Tensor x: encoder hidden state sequences (B, Tmax, Henc)
        :param namespace recog_args: argument namespace containing options
        :param list char_list: list of characters
        :param torch.nn.Module rnnlm: language model module
        :return: N-best decoding results
        :rtype: list
        """
        raise NotImplementedError("Batch decoding is not supported yet.")
```
请问是链接的文件不对吗

**Comment by houwenxin** [comment]
Hi，请问您使用的是我们提供的Docker内的Espnet版本么，我们使用的是自己实现的Batch Decoding版本

**Comment by suuuuju** [comment]
> Hi，请问您使用的是我们提供的Docker内的Espnet版本么，我们使用的是自己实现的Batch Decoding版本

因为在RTX3090上配置环境遇到了一点问题就替换成了官方最新版的espnet，您的意思是说镜像中所带的espnet是实现了Batch Decoding的吗

**Comment by suuuuju** [comment]
> Hi，请问您使用的是我们提供的Docker内的Espnet版本么，我们使用的是自己实现的Batch Decoding版本

问题已解决，非常感谢
